// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: birds.sql

package database

import (
	"context"
	"database/sql"
)

const createBird = `-- name: CreateBird :one
INSERT INTO birds  (id, created_at, updated_at, common_name, scientific_name, family, "order", status)
VALUES ( 
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5
) ON CONFLICT (common_name) DO UPDATE SET updated_at = NOW(), status = $5
RETURNING id, created_at, updated_at, common_name, scientific_name, family, "order", status
`

type CreateBirdParams struct {
	CommonName     sql.NullString
	ScientificName sql.NullString
	Family         sql.NullString
	Order          sql.NullString
	Status         sql.NullString
}

func (q *Queries) CreateBird(ctx context.Context, arg CreateBirdParams) (Bird, error) {
	row := q.db.QueryRowContext(ctx, createBird,
		arg.CommonName,
		arg.ScientificName,
		arg.Family,
		arg.Order,
		arg.Status,
	)
	var i Bird
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommonName,
		&i.ScientificName,
		&i.Family,
		&i.Order,
		&i.Status,
	)
	return i, err
}
