// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bird struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CommonName     sql.NullString
	ScientificName sql.NullString
	Family         sql.NullString
	Order          sql.NullString
	Status         sql.NullString
}
