// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const danger_ResetRatingsDB = `-- name: Danger_ResetRatingsDB :exec
UPDATE ratings
set rating = 1000,
updated_at = NOW(),
created_at = NOW(),
matches = 0
`

func (q *Queries) Danger_ResetRatingsDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, danger_ResetRatingsDB)
	return err
}

const getRatingByBirdID = `-- name: GetRatingByBirdID :one
SELECT id, created_at, updated_at, matches, rating, bird_id, common_name from ratings
WHERE bird_id = $1
`

func (q *Queries) GetRatingByBirdID(ctx context.Context, birdID uuid.UUID) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRatingByBirdID, birdID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Matches,
		&i.Rating,
		&i.BirdID,
		&i.CommonName,
	)
	return i, err
}

const getTopRatings = `-- name: GetTopRatings :many
SELECT id, created_at, updated_at, matches, rating, bird_id, common_name from ratings
ORDER BY rating DESC
LIMIT $1
`

func (q *Queries) GetTopRatings(ctx context.Context, limit int32) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, getTopRatings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Matches,
			&i.Rating,
			&i.BirdID,
			&i.CommonName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalRatings = `-- name: GetTotalRatings :one
SELECT count(*) from ratings
`

func (q *Queries) GetTotalRatings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalRatings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const populateRating = `-- name: PopulateRating :exec
INSERT INTO ratings (
    id,
    created_at,
    updated_at,
    matches,
    rating,
    bird_id
) VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
) ON CONFLICT (bird_id) DO NOTHING
`

type PopulateRatingParams struct {
	Matches sql.NullInt32
	Rating  sql.NullInt32
	BirdID  uuid.UUID
}

func (q *Queries) PopulateRating(ctx context.Context, arg PopulateRatingParams) error {
	_, err := q.db.ExecContext(ctx, populateRating, arg.Matches, arg.Rating, arg.BirdID)
	return err
}

const updateRatingByBirdID = `-- name: UpdateRatingByBirdID :one
UPDATE ratings
set rating = $1,
updated_at = NOW(),
matches = matches + 1
WHERE bird_id = $2
RETURNING id, created_at, updated_at, matches, rating, bird_id, common_name
`

type UpdateRatingByBirdIDParams struct {
	Rating sql.NullInt32
	BirdID uuid.UUID
}

func (q *Queries) UpdateRatingByBirdID(ctx context.Context, arg UpdateRatingByBirdIDParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRatingByBirdID, arg.Rating, arg.BirdID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Matches,
		&i.Rating,
		&i.BirdID,
		&i.CommonName,
	)
	return i, err
}
