// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const populateRating = `-- name: PopulateRating :exec
INSERT INTO ratings (
    id,
    created_at,
    updated_at,
    matches,
    rating,
    bird_id
) VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
) ON CONFLICT (bird_id) DO NOTHING
`

type PopulateRatingParams struct {
	Matches sql.NullInt32
	Rating  sql.NullInt32
	BirdID  uuid.UUID
}

func (q *Queries) PopulateRating(ctx context.Context, arg PopulateRatingParams) error {
	_, err := q.db.ExecContext(ctx, populateRating, arg.Matches, arg.Rating, arg.BirdID)
	return err
}
